### ISSUE TITLE
Not working on background tabs

### ISSUE THREAD

**Issue by dhaern** [ChronixPsyc/PoE2InstaWhisper#2]
Tested with Edge (Chromium based) and Librewolf (Firefox based), when the tabs are in background autoclick stop working after some time. Memory saving, sleeping tabs and every efficiency mode is disabled.

You can test just leaving some tabs in background for some minutes and this will stop working.

![Image](https://github.com/user-attachments/assets/f6a4aafe-0dc9-4709-b58e-6eb59dd76d29)

**Edit:** Tested aswell with separate windows instead tabs and still not working, looks like the windows need to be in foreground all time.

**Comment by ChronixPsyc** [comment]
Chrome issue should be fixed. Added an alarm message to activate the tab every 15 seconds to keep it awake.

Firefox seems to not allow keeping inactive tabs active. The only way I can see doing this would be to use the Firefox development edition and in `about:config` set `dom.timeout.background_throttling_max_budget` to `-1`.

Reddit says there are addons for Firefox that keep the tabs active for you so that might be the best approach.

**Comment by dhaern** [comment]
For whatever reason, tabs or windows in background still not working with new version AND aswell tested with this always active windows extension for Chrome:

https://chromewebstore.google.com/detail/always-active-window-alwa/ehllkhjndgnlokhomdlhgbineffifcbj
